site_name: My SQL Workbench User Doc
theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
- Home: "index.md"
- Manage Relational Databases with SQL Operations: "task1.md"
- Join tables into a view for future reference: "task2.md"
- Create and drop triggers: "task3.md"
- Troubleshooting: "troubleshooting.md"
- Glossary: "glossary.md"
